"""initial

Revision ID: 71ff415e588e
Revises:
Create Date: 2025-11-11 11:54:26.574417

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71ff415e588e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animes",
        sa.Column("mal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title_ro", sa.String(), nullable=False),
        sa.Column("poster_url", sa.String(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("NORMAL", "FINALIZED", "BLACKLISTED", name="animestatus"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("mal_id", name=op.f("pk_animes")),
    )
    op.create_table(
        "anime_infos",
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.mal_id"], name=op.f("fk_anime_infos_anime_id_animes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anime_infos")),
    )
    op.create_table(
        "songs",
        sa.Column("anime_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.Enum("OP", "ED", name="category"), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("song_artist", sa.String(), nullable=False),
        sa.Column("song_name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.mal_id"], name=op.f("fk_songs_anime_id_animes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_songs")),
        sa.UniqueConstraint("anime_id", "category", "number", name=op.f("uq_songs_anime_id")),
    )
    op.create_table(
        "levels",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("value >= 0 AND value <= 100", name=op.f("ck_levels_value_range")),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], name=op.f("fk_levels_song_id_songs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_levels")),
    )
    op.create_table(
        "sources",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("local_path", sa.String(), nullable=True),
        sa.Column(
            "status", sa.Enum("NORMAL", "INVALID", "DOWNLOADING", "DOWNLOADED", name="sourcestatus"), nullable=False
        ),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], name=op.f("fk_sources_song_id_songs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "timings",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("guess_start", sa.Float(), nullable=False),
        sa.Column("reveal_start", sa.Float(), nullable=False),
        sa.Column("added_by", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], name=op.f("fk_timings_source_id_sources")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timings")
    op.drop_table("sources")
    op.drop_table("levels")
    op.drop_table("songs")
    op.drop_table("anime_infos")
    op.drop_table("animes")
    sa.Enum(name="category").drop(op.get_bind())
    sa.Enum(name="animestatus").drop(op.get_bind())
    sa.Enum(name="sourcestatus").drop(op.get_bind())
    # ### end Alembic commands ###
