"""empty message

Revision ID: 6d6691d11fdd
Revises: e662cadf374c
Create Date: 2026-01-03 12:47:39.373853

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d6691d11fdd"
down_revision: Union[str, Sequence[str], None] = "e662cadf374c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE platform ADD VALUE 'ANILIST'")
    op.execute("ALTER TYPE platform ADD VALUE 'ANIMENEWSNETWORK'")
    op.drop_table("anime_infos")
    op.drop_constraint(op.f("uq_id_mappings_value_platform"), "id_mappings", type_="unique")
    op.create_unique_constraint(op.f("uq_id_mappings_value"), "id_mappings", ["value", "platform"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_id_mappings_value"), "id_mappings", type_="unique")
    op.create_unique_constraint(
        op.f("uq_id_mappings_value_platform"), "id_mappings", ["value", "platform"], postgresql_nulls_not_distinct=False
    )
    op.create_table(
        "anime_infos",
        sa.Column("anime_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("data", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["anime_id"], ["animes.id"], name=op.f("fk_anime_infos_anime_id_animes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anime_infos")),
    )
    # ### end Alembic commands ###
